AllCops:
  Exclude:
    - 'bin/*'

Style/BracesAroundHashParameters:
      EnforcedStyle: context_dependent

LineLength:
  Enabled: true
  Max: 200

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Max: 100